// auth
export const LOGIN_SUCCESS = 'LOGIN'
export const LOGOUT_SUCCESS = 'LOGOUT'

// update state actions
export const UPDATE_USER_ROOM_PRESENCE = 'UPDATE_USER_ROOM_PRESENCE'
export const UPDATE_ROOM_PRESENCES = 'UPDATE_ROOM_PRESENCES'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const UPDATE_ROOM = 'UPDATE_ROOM'
export const UPDATE_AVAILABLE_ROOMS = 'UPDATE_AVAILABLE_ROOMS'

// room related events
export const ACTIVE_ROOM = 'ACTIVE_ROOM'
export const SEND_MESSAGE = 'SEND_MESSAGE'


export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR'

export const FETCH_ROOM_USERS_REQUEST = 'FETCH_ROOM_USERS_REQUEST'
export const FETCH_ROOM_USERS_SUCCESS = 'FETCH_ROOM_USERS_SUCCESS'
export const FETCH_ROOM_USERS_FAILURE = 'FETCH_ROOM_USERS_FAILURE'

// saga triggers
export const FETCH_MORE_MESSAGES_SAGA = 'FETCH_MORE_MESSAGES_SAGA'
export const JOIN_ROOM_SAGA = 'JOIN_ROOM_SAGA'
export const LEAVE_ROOM_SAGA = 'LEAVE_ROOM_SAGA'
export const INIT_SLACKER_SAGA = 'INIT_SLACKER_SAGA'
